package br.com.compiler.portugolo.common;


public class Tag {
    public final static int EOF = 1,
            ID = 3,
            NUMERICO_INT = 6,
            NUMERICO_REAL = 8,
            CONST_STRING = 10,
            PONTO_VIRGULA = 11,
            ABRE_PARENTESES = 12,
            FECHA_PARENTESES = 13,
            ABRE_COLCHETES = 14,
            FECHA_COLCHETES = 15,
            VIRGULA = 16,
            MAIOR_IGUAL = 18,
            MAIOR = 19,
            MENOR_IGUAL = 21,
            DIFERENTE = 22,
            ATRIBUICAO = 24,
            MENOR = 25,
            IGUAL = 26,
            DIVISAO = 28,
            MULTIPLICACAO = 33,
            SUBTRACAO = 34,
            ADICAO = 35,
            ALGORITMO = 50,
            DECLARE = 51,
            FIM = 52,
            SUBROTINA = 53,
            RETORNE = 54,
            TIPO_LOGICO = 55,
            TIPO_NUMERICO = 56,
            TIPO_LITERAL = 57,
            TIPO_DANADANAO = 58,
            NAO = 59,
            SE = 60,
            INICIO = 61,
            SENAO = 62,
            ENQUANTO = 63,
            FACA = 64,
            PARA = 65,
            ATE = 66,
            REPITA = 67,
            ESCREVA = 68,
            LEIA = 69,
            VERDADEIRO = 70,
            FALSO = 71,
            OU = 72,
            E = 73,
            VAZIO = 80,
            ERRO = 81;
}
